### ISSUE TITLE
Uncaught TypeError: parent.querySelectorAll is not a function

### ISSUE THREAD

**Issue by duclet** [NutterV/atom-tree-view-auto-fold#2]
[Enter steps to reproduce:]

1. Opening any file.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Linux Mint
**Thrown From**: [tree-view-auto-fold](https://github.com/NutterV/atom-tree-view-auto-fold) package 1.1.0

### Stack Trace

Uncaught TypeError: parent.querySelectorAll is not a function

```
At /mnt/app-data/atom/data/packages/tree-view-auto-fold/lib/treeviewui.coffee:215

TypeError: parent.querySelectorAll is not a function
    at TreeViewUI.module.exports.TreeViewUI.removeAllAddedClasses (/packages/tree-view-auto-fold/lib/treeviewui.coffee:215:5)
    at TreeViewUI.module.exports.TreeViewUI.updateRoots (/packages/tree-view-auto-fold/lib/treeviewui.coffee:240:8)
    at TreeViewUI.module.exports.TreeViewUI.entryClicked (/packages/tree-view-auto-fold/lib/treeviewui.coffee:173:12)
    at /packages/tree-view-auto-fold/lib/treeviewui.coffee:63:8)
```

### Commands

```
  7x -0:23.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-2-dark-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
2-dark-syntax 1.1.0 
atom-beautify 0.29.26 
atom-handlebars 1.3.0 
atom-html-preview 0.1.22 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
autohide-tree-view 0.25.1 
busy-signal 1.4.3 
docblockr 0.10.3 
duplicate-removal 0.1.3 
highlight-selected 0.13.1 
intentions 1.1.2 
language-javascript-jsx 0.3.7 
language-nginx 0.8.0 
line-ending-converter 1.3.2 
linter 2.1.4 
linter-eslint 8.2.1 
linter-jshint 3.1.2 
linter-ui-default 1.6.0 
markdown-themeable-pdf 1.2.0 
merge-conflicts 1.4.5 
pdf-view 0.58.0 
sort-lines 0.14.0 
split-diff 1.4.0 
tree-view-auto-fold 1.1.0 
tree-view-autoresize 2.1.0 
tree-view-panes 0.3.5 
```

**Comment by NutterV** [comment]
I believe I've fixed this, please can you re-check

**Comment by duclet** [comment]
The issue still comes up here:

https://github.com/NutterV/atom-tree-view-auto-fold/blob/b39588eb4f3a0042f6e52f2a5bcb8f58be6315b1/lib/treeviewui.coffee#L245

What I'm seeing though while looking at the code is that it seems like you are defaulting parent to something if it is not given but it looks like the defaulting thing is not working. Looking at the transpiled code, the check for putting the default value is a comparison against "null" but in most of these cases, it's value is "undefined".

**Comment by NutterV** [comment]
I believe I've fixed this again, try catches to basically stop attempting to do the querySelectorAll function on non-DOM elements. The structure of the original tree-view which I'm overlaying seems to have very odd behaviors at random times.

**Comment by duclet** [comment]
It is fixed.

**Comment by NutterV** [comment]
Just wanted to ask, how you are finding the package, are you finding it useful?

**Comment by duclet** [comment]
Yes I do. It keeps the tree-view much smaller to only files I cared about. I also like the fact that it keeps files that are modified in Git shown even if it is not opened. Thanks.
